### ISSUE TITLE
spec failure returns exit status 0

### ISSUE THREAD

**Issue by chrisb87** [sporkrb/spork#103] opened 2011-04-13 18:17 UTC
I am using spork with rspec2 and watchr. I would like to detect if the specs passed or not in my watchr script, but spork seems to always return exit status 0 even when specs fail. RSpec does return the correct exit status when not used with spork.

**Comment by rdp** [comment] 2011-04-13 18:50
why is spork exiting at all?

**Comment by chrisb87** [comment] 2011-04-13 19:07
You're right, spork never exits :) The exit status is actually coming from the rspec command. So "rspec spec_dir" returns the correct exit status, as does "rspec --drb spec_dir" without spork running, but "rspec --drb spec_dir" with spork running always returns 0.

I fear this is the type of issue where the spork developers will say it's an rspec problem, and the rspec developers will say it's a spork problem. Wherever the problem may lie, let's work on solving it!

**Comment by timcharper** [comment] 2011-05-06 17:43
Yeah, this is may be on the rspec side / both sides.  We may need to collaborate with them to see if we are providing enough information to let them know it failed.

**Comment by timcharper** [comment] 2011-05-06 17:52
Ok, it looks like it's a change needed on rspec.  Here's what's going on

rspec calls `Spork::Server#run` via DRB, passing in args, stderr and stdout.

Eventually, spork calls `Spork::TestFramework::RSpec#run_tests`, which then calls `::Spec::Runner::CommandLine#run` with the same args, stderr and stdout it received.

When `::Spec::Runner::CommandLine#run` finishes, it returns `true` if all specs passed, and `false` if all specs didn't pass.  I've confirmed that `Spork::Server#run` ultimately returns this value via DRB back to the rspec drb client.

What needs to happen is the rspec drb client should take this result and modify the exit status based on the result: 1 if false (errors happened), 0 if true (all good).

Can you pass this on to the rspec team?  It should be a simple fix.

**Comment by chrisb87** [comment] 2011-05-06 20:52
I [opened a ticket](https://github.com/rspec/rspec-core/issues/366) in the rspec project

**Comment by timcharper** [comment] 2011-05-12 16:07
Great, I'm going to close this one. Thanks!

**Closed as completed by timcharper** 2011-05-12 16:07 UTC
